services:
  web:
    build:
      context: .
      dockerfile: application.Dockerfile
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - env.list
    depends_on:
      - db

  db:
    image: postgres:16
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - env.list

volumes:
  pgdata:
  static_volume:
  media_volume:
