services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/django.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
      - media_volume:/app/media
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot-renew.sh:/usr/local/bin/certbot-renew.sh
    entrypoint: /usr/local/bin/certbot-renew.sh
    depends_on:
      - nginx
